{% set name = "python-gmatelastoplastic" %}
{% set version = "0.1.0" %}
{% set sha256 = "e66347d1c1e596da67069f618752585d94e4dca10fcb3a11cef5232d1fdf7d8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
  run:
    - python

test:
  imports:
    - GMatElastoPlastic

about:
  home: https://github.com/tdegeus/GMatElastoPlastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Elasto-plastic material model (Python wrapper).'
  description: 'Elasto-plastic material model (Python wrapper).'
  doc_url: https://github.com/tdegeus/GMatElastoPlastic
  dev_url: https://github.com/tdegeus/GMatElastoPlastic

extra:
  recipe-maintainers:
    - tdegeus
