{% set name = "python-gmatelastoplastic" %}
{% set version = "0.2.1" %}
{% set sha256 = "c6a2d10c5ebc0a85c49487c474a1f42ccc1301edbdf85ac0cd6b878eba37a844" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - gmattensor
    - gmatelastic
  run:
    - python

test:
  imports:
    - GMatElastoPlastic

about:
  home: https://github.com/tdegeus/GMatElastoPlastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic material model (Python wrapper).
  description: Elasto-plastic material model (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastoPlastic
  dev_url: https://github.com/tdegeus/GMatElastoPlastic

extra:
  recipe-maintainers:
    - tdegeus
