{% set name = "python-gmatelastoplastic" %}
{% set version = "0.2.0" %}
{% set sha256 = "dae10130d34b4ecb17dae0eed17cdc96f6f008c0b93a24a086f0793d7372823b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
  run:
    - python

test:
  imports:
    - GMatElastoPlastic

about:
  home: https://github.com/tdegeus/GMatElastoPlastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic material model (Python wrapper).
  description: Elasto-plastic material model (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastoPlastic
  dev_url: https://github.com/tdegeus/GMatElastoPlastic

extra:
  recipe-maintainers:
    - tdegeus
